services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - imbedding-net
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx_proxy_acme
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=admin@log8.kr
      - NGINX_PROXY_CONTAINER=nginx_proxy
    networks:
      - imbedding-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh

  embedding_api:
    build:
      context: ./imbedding
    container_name: embedding_api
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - imbedding-net
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=embed.log8.kr
      - LETSENCRYPT_HOST=embed.log8.kr
      - LETSENCRYPT_EMAIL=admin@log8.kr
      - VIRTUAL_PORT=5001
    env_file:
      - ./env

  redis:
    image: redis:7-alpine
    container_name: my_redis
    restart: unless-stopped
    networks:
      - imbedding-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  omechu_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=omechu1234
      - MYSQL_DATABASE=omechu_db
      - MYSQL_USER=omechu1234
      - MYSQL_PASSWORD=omechu1234
    container_name: omechu_db
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - imbedding-net
    volumes:
      - omechu_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  imbedding-net:

volumes:
  certs:
  vhost:
  html:
  acme:
  redis_data:
  omechu_db_data:
