services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - imbedding-net
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=admin@log8.kr
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - imbedding-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh

  embedding_api:
    build:
      context: ./imbedding
    container_name: embedding-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - imbedding-net
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=embed.log8.kr
      - LETSENCRYPT_HOST=embed.log8.kr
      - LETSENCRYPT_EMAIL=admin@log8.kr
      - VIRTUAL_PORT=5001

  redis:
    image: redis:7-alpine
    container_name: my-redis
    restart: unless-stopped
    networks:
      - imbedding-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
networks:
  imbedding-net:

volumes:
  certs:
  vhost:
  html:
  acme:
  redis_data:
